server:
  port: 8085

spring:
  application:
    name: content-service
  r2dbc:
    url: r2dbc:postgresql://sonifoy-db:5432/content_db
    username: sonifoy_user
    password: sonifoy_password

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

cloud:
  aws:
    s3:
      endpoint: http://minio:9000
      region: us-east-1
      access-key: sonifoy_minio
      secret-key: sonifoy_minio_password
      bucket-name: sonifoy-content
